export const environment = {
  production: false,
  availableStates: ["Running", "Active", "Waiting", "Complete", "Error", "Paused", "Removed"],
  previewWidth: '720px',
  previewHeight: '510px',
  supportedFeaturesWidth: "350px",
  supportedFeaturesHeight: "400px",
  sessionInfoWidth: "400px",
  sessionInfoHeight: "170px",
  downloadsPath: '/downloads',
  baseURL: 'http://localhost:3000/api',
  versionURL: '/version',
  fetchFeedURL: '/fetchFeed',
  addUriURL: '/addUri',
  addUrisURL: '/addUris',
  pauseDownloadURL: '/pauseDownload',
  unPauseDownloadURL: '/unPauseDownload',
  pauseAllDownloadsURL: '/pauseAllDownloads',
  unPauseAllDownloadsURL: '/unPauseAllDownloads',
  sessionInfoURL: '/sessionInfo',
  removeDownloadURL: '/removeDownload',
  forceRemoveDownloadURL: '/forceRemoveDownload',
  removeDownloadResultURL: '/removeDownloadResult',
  forcePauseDownloadURL: '/forcePauseDownload',
};
